from contextlib import AbstractContextManager
from typing import Protocol

from app.domain.members import StoredMember, StoredSession


class MemberTransaction(Protocol):
    def find_identity(self, identity: str) -> StoredMember | None: ...

    def get_member(self, member_id: str) -> StoredMember | None: ...

    def insert_member(self, member: StoredMember) -> None: ...

    def update_profile(
        self, member: StoredMember, username: str, email: str
    ) -> None: ...

    def update_password(self, member: StoredMember, password_hash: str) -> None: ...

    def get_session(self, token_hash: str) -> StoredSession | None: ...

    def insert_session(self, session: StoredSession, limit: int) -> None: ...

    def delete_session(self, token_hash: str) -> None: ...

    def revoke_sessions(self, member_id: str, keep: str | None = None) -> None: ...

    def delete_expired_sessions(self, now: int) -> None: ...


class MemberStore(Protocol):
    # Updates and session revocations must commit or roll back together.
    def transaction(self) -> AbstractContextManager[MemberTransaction]: ...


class RateLimiter(Protocol):
    def allow(self, key: str, limit: int, window_seconds: int) -> bool: ...
