STORE_METADATA = {
    "森森買取": {
        "website_url": "https://www.morimori-kaitori.jp",
        "address": "〒101-0021 東京都千代田区外神田5-1-5 ACN秋葉原PLACE 1F",
        "phone": "050-1725-1643",
        "summary": "iPhoneやゲーム機などを扱い、秋葉原・大阪・福岡に店舗と郵送窓口を展開する買取店です。",
        "is_sponsored": False,
    },
    "買取商店": {
        "website_url": "https://www.kaitorishouten-co.jp",
        "address": "〒171-0022 東京都豊島区南池袋1-22-1 池袋1221ビル1F",
        "phone": "03-6869-0330",
        "summary": "スマートフォン、家電、日用品を扱い、都内の複数店舗と宅配買取に対応しています。",
        "is_sponsored": False,
    },
    "モバイル一番": {
        "website_url": "https://www.mobile-ichiban.com",
        "address": "〒171-0021 東京都豊島区西池袋1-29-5 山の手ビル1F",
        "phone": "03-6912-6085",
        "summary": "スマートフォンや家電を扱い、池袋などの店舗と郵送買取に対応しています。",
        "is_sponsored": False,
    },
    "携帯空間": {
        "website_url": "https://www.keitaispace.co.jp",
        "address": "〒116-0013 東京都荒川区西日暮里2-17-10 アクセスキクヤビル1F",
        "phone": "03-6806-7031",
        "summary": "携帯電話やタブレット、ゲーム機などの店頭・郵送買取に対応しています。",
        "is_sponsored": False,
    },
    "トゥインクル": {
        "website_url": "https://twinkle-mobile.com",
        "address": "〒101-0021 東京都千代田区外神田3-7-14 中部電材ビル101",
        "phone": "03-3525-8818",
        "summary": "スマートフォンやゲーム機などを扱い、秋葉原の店舗と郵送買取に対応しています。",
        "is_sponsored": False,
    },
    "買取一丁目": {
        "website_url": "https://www.1-chome.com",
        "address": "〒101-0021 東京都千代田区外神田1-16-10 ニュー秋葉原センタービル1F 11号",
        "phone": "03-6811-6668",
        "summary": "スマートフォンや家電などを扱い、複数の店舗と郵送買取に対応しています。",
        "is_sponsored": True,
    },
    "モバステ": {
        "website_url": "https://pastec.net",
        "address": "〒101-0021 東京都千代田区外神田1-9-9 内田ビル5F",
        "phone": "03-6206-0115",
        "summary": "iPhoneなどのスマートフォンを扱い、全国の店舗と宅配買取に対応しています。",
        "is_sponsored": False,
    },
    "モバイルミックス": {
        "website_url": "https://mobile-mix.jp",
        "address": "〒101-0021 東京都千代田区外神田4-4-2 HULIC &New AKIHABARA 1F",
        "phone": "03-3525-7222",
        "summary": "携帯電話、タブレット、ゲーム機などの店頭・郵送買取に対応しています。",
        "is_sponsored": False,
    },
    "買取楽園": {
        "website_url": "https://www.keitairakuen.com/shop/",
        "address": "〒151-0053 東京都渋谷区代々木2-23-1 ニュー・ステイト・メナー276号室",
        "phone": "03-6276-3804",
        "summary": "携帯電話やゲーム機などを扱い、新宿の店舗と郵送買取に対応しています。",
        "is_sponsored": False,
    },
    "ドラゴンモバイル": {
        "website_url": "https://mobileone.co.jp",
        "address": "〒101-0025 東京都千代田区神田佐久間町1-14 第二東ビル1F 廊下101",
        "phone": "03-5207-2927",
        "summary": "スマートフォン、タブレット、家電などの店頭・郵送買取に対応しています。",
        "is_sponsored": False,
    },
    "買取ベストワン": {
        "website_url": "https://kaitoribestone.com",
        "address": "〒120-0034 東京都足立区千住3-6-12 ツオード千住壱番館1002号室",
        "phone": "03-5284-7926",
        "summary": "スマートフォンやゲーム機などを扱い、店頭・宅配買取に対応しています。",
        "is_sponsored": False,
    },
    "買取ルデヤ": {
        "website_url": "https://kaitori-rudeya.com",
        "address": "〒115-0045 東京都北区赤羽1-3-6 詩音堂ビル1階",
        "phone": "03-5939-6122",
        "summary": "スマートフォンや家電などを扱い、複数の店舗と宅配買取に対応しています。",
        "is_sponsored": False,
    },
    "ヤマダ電機": {
        "website_url": "https://www.yamada-denki.jp",
        "address": "〒370-0841 群馬県高崎市栄町1-1",
        "phone": "0570-078-181",
        "summary": "家電量販店として、対象店舗やオンラインでスマートフォンなどの買取に対応しています。",
        "is_sponsored": False,
    },
    "買取wiki": {
        "website_url": "https://kaitori.wiki",
        "address": "〒121-0836 東京都足立区入谷4-20-7",
        "phone": "03-6458-3460",
        "summary": "スマートフォン、パソコン、家電などの店頭・宅配買取に対応しています。",
        "is_sponsored": False,
    },
    "買取BASE": {
        "website_url": "https://iphone-base.net",
        "address": "〒210-0007 神奈川県川崎市川崎区駅前本町26-2 アゼリア地下街 スマップル川崎店内",
        "phone": "050-3134-3959",
        "summary": "iPhoneやiPadなどのApple製品を中心に、店頭・郵送買取に対応しています。",
        "is_sponsored": False,
    },
    "アキモバ": {
        "website_url": "https://www.akiba-mobile.co.jp",
        "address": "〒101-0021 東京都千代田区外神田3-11-11 VORT秋葉原VI 1F",
        "phone": "03-6206-0106",
        "summary": "スマートフォン、タブレット、ゲーム機などの店頭・郵送買取に対応しています。",
        "is_sponsored": False,
    },
    "買取ホムラ": {
        "website_url": "https://kaitori-homura.com",
        "address": "〒101-0023 東京都千代田区神田松永町16 横川ビル1F",
        "phone": "03-6262-9977",
        "summary": "スマートフォン、ゲーム機、家電などを扱い、複数店舗で買取に対応しています。",
        "is_sponsored": False,
    },
    "買取当番": {
        "website_url": "https://tobansyoji.co.jp",
        "address": "〒101-0021 東京都千代田区外神田1-2-9 ラオックス秋葉原本店5F",
        "phone": "070-9209-3267",
        "summary": "スマートフォンや家電などを扱い、秋葉原・池袋の店舗と郵送買取に対応しています。",
        "is_sponsored": False,
    },
    "買取レッド": {
        "website_url": "https://kaitori-red.com",
        "address": "〒150-0042 東京都渋谷区宇田川町12-3 ニュー渋谷コーポラス404号",
        "phone": "03-6386-5357",
        "summary": "公式サイトで買取方法や営業情報を案内している渋谷の買取店です。",
        "is_sponsored": False,
    },
    "PANDA買取": {
        "website_url": "https://panda-kaitori.co.jp",
        "address": "〒116-0014 東京都荒川区東日暮里1-17-11 南エンタープライズ東日暮里1F",
        "phone": "03-5615-2780",
        "summary": "スマートフォンや家電などを扱い、店頭・郵送買取に対応しています。",
        "is_sponsored": False,
    },
    "ケータイゴット": {
        "website_url": "https://keitai-god.com",
        "address": "〒160-0023 東京都新宿区西新宿1-18-17 ラウンドクロス西新宿7F",
        "phone": "03-5324-6101",
        "summary": "携帯電話やタブレットなどを扱い、新宿・池袋の店舗と宅配買取に対応しています。",
        "is_sponsored": False,
    },
    "ゲストモバイル": {
        "website_url": "https://www.guestmobile.jp",
        "address": "〒252-0231 神奈川県相模原市中央区相模原5-5-6 グランドメゾン相模原2F",
        "phone": "042-851-4812",
        "summary": "携帯電話、ゲーム機、家電などを扱い、店頭・郵送買取に対応しています。",
        "is_sponsored": False,
    },
    "買取ソムリエ": {
        "website_url": "https://somurie-kaitori.com",
        "address": "〒658-0032 兵庫県神戸市東灘区向洋町中6-9 神戸ファッションマート7F 7N-09号室",
        "phone": "078-855-8999",
        "summary": "スマートフォン、家電、ゲーム機などを扱い、宅配買取に対応しています。",
        "is_sponsored": False,
    },
    "家電市場": {
        "website_url": "https://www.kaden-ichiba.com",
        "address": "〒356-0056 埼玉県ふじみ野市うれし野2-15-5",
        "phone": "049-250-8009",
        "summary": "家電、スマートフォン、ゲーム機などの店頭・出張・宅配買取に対応しています。",
        "is_sponsored": False,
    },
    "アバウテック": {
        "website_url": "https://www.aboutec.jp",
        "address": "〒110-0016 東京都台東区台東2-10-1 1F",
        "phone": "03-5812-3453",
        "summary": "パソコン、スマートフォン、家電などの店頭・宅配買取に対応しています。",
        "is_sponsored": False,
    },
}


def get_store_metadata(name: str) -> dict:
    return STORE_METADATA.get(name, {})
